### ISSUE TITLE
System.ArgumentOutOfRangeException: Value 1604 is too large for LineInfo.TextAt

### ISSUE THREAD

**Issue by icsantos** [zooba/indentguide#19]
Exception raised at 8/18/2021 4:34:29 PM:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Value 1604 is too large for LineInfo.TextAt
   at IndentGuide.DocumentAnalyzer.LineInfo.set_TextAt(Int32 value)
   at IndentGuide.DocumentAnalyzer.SetLineInfo(LineInfo[] lineInfo, ITextSnapshot snapshot, Int32 firstLine, Int32 lastLine, CancellationToken cancel)
   at IndentGuide.DocumentAnalyzer.<ResetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IndentGuide.DocumentAnalyzer.<UpdateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IndentGuide.IndentGuideView.<AnalyzeAndUpdateAdornmentsAsync>d__10.MoveNext()

**Comment by zooba** [comment]
Should probably just not display anything at this distance. No need to raise - the noisy signal was mainly to catch issues at "reasonable" lengths, which don't appear to be there.

**Comment by dbgarlisch** [comment]
Loading a 37MB XML file triggered this same message for me:

```
Exception raised at 8/9/2022 6:38:31 PM:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Value 1048576 is too large for LineInfo.Number
   at IndentGuide.DocumentAnalyzer.LineInfo.set_Number(Int32 value)
   at IndentGuide.DocumentAnalyzer.SetLineInfo(LineInfo[] lineInfo, ITextSnapshot snapshot, Int32 firstLine, Int32 lastLine, CancellationToken cancel)
   at IndentGuide.DocumentAnalyzer.<ResetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IndentGuide.IndentGuideView.<AnalyzeAndUpdateAdornmentsAsync>d__10.MoveNext()
```
